INSERT INTO ingredients_reference (name, category, user_id, all_users)
VALUES
    ('Salt', 'Spices & Seasonings', null, true),
    ('Black Pepper', 'Spices & Seasonings', null, true),
    ('Olive Oil', 'Oils & Fats', null, true),
    ('Vegetable Oil', 'Oils & Fats', null, true),
    ('Butter', 'Dairy', null, true),
    ('Garlic', 'Vegetables', null, true),
    ('Onion', 'Vegetables', null, true),
    ('Tomatoes', 'Vegetables', null, true),
    ('Flour', 'Baking & Grains', null, true),
    ('Granulated Sugar', 'Baking & Grains', null, true),
    ('Brown Sugar', 'Baking & Grains', null, true),
    ('Honey', 'Condiments & Sweeteners', null, true),
    ('Milk', 'Dairy', null, true),
    ('Eggs', 'Dairy', null, true),
    ('Baking Powder', 'Baking & Grains', null, true),
    ('Baking Soda', 'Baking & Grains', null, true),
    ('Vanilla Extract', 'Baking & Grains', null, true),
    ('Cocoa Powder', 'Baking & Grains', null, true),
    ('Chicken Broth', 'Canned & Jarred', null, true),
    ('Beef Broth', 'Canned & Jarred', null, true),
    ('Vegetable Broth', 'Canned & Jarred', null, true),
    ('Rice', 'Baking & Grains', null, true),
    ('Pasta', 'Baking & Grains', null, true),
    ('Bread', 'Baking & Grains', null, true),
    ('Cheddar Cheese', 'Dairy', null, true),
    ('Parmesan Cheese', 'Dairy', null, true),
    ('Mozzarella Cheese', 'Dairy', null, true),
    ('Chicken Breast', 'Meat', null, true),
    ('Ground Beef', 'Meat', null, true),
    ('Pork Chops', 'Meat', null, true),
    ('Salmon', 'Seafood', null, true),
    ('Shrimp', 'Seafood', null, true),
    ('Potatoes', 'Vegetables', null, true),
    ('Carrots', 'Vegetables', null, true),
    ('Celery', 'Vegetables', null, true),
    ('Bell Peppers', 'Vegetables', null, true),
    ('Zucchini', 'Vegetables', null, true),
    ('Spinach', 'Vegetables', null, true),
    ('Broccoli', 'Vegetables', null, true),
    ('Cauliflower', 'Vegetables', null, true),
    ('Lettuce', 'Vegetables', null, true),
    ('Cucumber', 'Vegetables', null, true),
    ('Mushrooms', 'Vegetables', null, true),
    ('Green Beans', 'Vegetables', null, true),
    ('Corn', 'Vegetables', null, true),
    ('Peas', 'Vegetables', null, true),
    ('Basil', 'Herbs & Spices', null, true),
    ('Parsley', 'Herbs & Spices', null, true),
    ('Cilantro', 'Herbs & Spices', null, true),
    ('Thyme', 'Herbs & Spices', null, true),
    ('Rosemary', 'Herbs & Spices', null, true),
    ('Oregano', 'Herbs & Spices', null, true),
    ('Dill', 'Herbs & Spices', null, true),
    ('Paprika', 'Spices & Seasonings', null, true),
    ('Cumin', 'Spices & Seasonings', null, true),
    ('Curry Powder', 'Spices & Seasonings', null, true),
    ('Chili Powder', 'Spices & Seasonings', null, true),
    ('Red Pepper Flakes', 'Spices & Seasonings', null, true),
    ('Cinnamon', 'Spices & Seasonings', null, true),
    ('Nutmeg', 'Spices & Seasonings', null, true),
    ('Ginger', 'Spices & Seasonings', null, true),
    ('Soy Sauce', 'Condiments & Sauces', null, true),
    ('Worcestershire Sauce', 'Condiments & Sauces', null, true),
    ('Mustard', 'Condiments & Sauces', null, true),
    ('Ketchup', 'Condiments & Sauces', null, true),
    ('Mayonnaise', 'Condiments & Sauces', null, true),
    ('Vinegar (White, Apple Cider, Balsamic)', 'Condiments & Sauces', null, true),
    ('Lemon Juice', 'Condiments & Sauces', null, true),
    ('Lime Juice', 'Condiments & Sauces', null, true),
    ('Apples', 'Fruits', null, true),
    ('Bananas', 'Fruits', null, true),
    ('Grapes', 'Fruits', null, true),
    ('Oranges', 'Fruits', null, true),
    ('Lemons', 'Fruits', null, true),
    ('Berries (Strawberries, Blueberries, etc.)', 'Fruits', null, true),
    ('Avocado', 'Fruits', null, true),
    ('Almonds', 'Nuts & Seeds', null, true),
    ('Walnuts', 'Nuts & Seeds', null, true),
    ('Chia Seeds', 'Nuts & Seeds', null, true),
    ('Flaxseeds', 'Nuts & Seeds', null, true),
    ('Yogurt', 'Dairy', null, true),
    ('Cream Cheese', 'Dairy', null, true),
    ('Sour Cream', 'Dairy', null, true),
    ('Heavy Cream', 'Dairy', null, true),
    ('Cornstarch', 'Baking & Grains', null, true),
    ('Tomato Paste', 'Canned & Jarred', null, true),
    ('Tomato Sauce', 'Canned & Jarred', null, true),
    ('Salsa', 'Condiments & Sauces', null, true),
    ('Tortillas', 'Baking & Grains', null, true),
    ('Hot Sauce', 'Condiments & Sauces', null, true),
    ('Jalapeños', 'Vegetables', null, true),
    ('Pickles', 'Canned & Jarred', null, true),
    ('Olives', 'Canned & Jarred', null, true),
    ('Feta Cheese', 'Dairy', null, true),
    ('Bacon', 'Meat', null, true),
    ('Sausage', 'Meat', null, true),
    ('Ham', 'Meat', null, true),
    ('Tofu', 'Protein Alternatives', null, true),
    ('Lentils', 'Baking & Grains', null, true),
    ('Quinoa', 'Baking & Grains', null, true);
